---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eth2-beaconchain-explorer
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "bloxcha.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - eth2-beaconchain-explorer
  http:
  - route:
    - destination:
        host: eth2-beaconchain-explorer-svc
        port:
          number: 3333
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: eth2-beaconchain-explorer
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "bloxcha.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: eth2-beaconchain-explorer-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: eth2-beaconchain-explorer
spec:
  type: ClusterIP
  ports:
    - port: 3333
      protocol: TCP
      targetPort: 3333
      name: port-3333
  selector:
    app: eth2-beaconchain-explorer
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: eth2-beaconchain-explorer
  name: eth2-beaconchain-explorer
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: eth2-beaconchain-explorer
  template:
    metadata:
      labels:
        app: eth2-beaconchain-explorer
    spec:
      containers:
      - name: eth2-beaconchain-explorer
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
          name: port-3333
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beaconcha_db_user

        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beaconcha_db_name

        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beaconcha_db_host

        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beaconcha_db_port

        - name: DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beaconcha_db_pass
